### ISSUE TITLE
Stuck on Finalising input tracks 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [tripathiarpan20/midiformers#1]
I am using my full instrumental midi of about 3 min runtime.
![image](https://user-images.githubusercontent.com/78225592/183263583-8de8bbbd-f8e7-47d5-b566-fe445cbfa46e.png)

**Comment by tripathiarpan20** [comment]
Hi,
If you closely there is a text box in the cell, follow the written instructions to run in the screenshot:
![image](https://user-images.githubusercontent.com/42506819/186829132-1117ba04-311a-43aa-9da4-be247bec9fa3.png)
