### ISSUE TITLE
NameError: name 'masked_oct_idxs' is not defined in "Call this to predict masks" cell

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [tripathiarpan20/midiformers#2]
`NameError                                 Traceback (most recent call last)
<ipython-input-139-9e6a982377a0> in <module>()
      1 # Call this to predict masks
      2 mask_prediction_output = predict_all_masks(roberta_base, label_dict, temperature_dict, masked_encoding,
----> 3                                           masked_octuples = masked_oct_idxs,
      4                                           mask_attribs = mask_attribs,
      5                                           prediction_mode = prediction_mode,

NameError: name 'masked_oct_idxs' is not defined`

**Comment by tripathiarpan20** [comment]
I think you haven't run all the cells.
We have written the relevant instructions in the notebook cell, please follow them and you would definitely be able to run the application.
