### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by asigalov61** [tripathiarpan20/midiformers#3]
Hey Arpan,

Thank you so much for this work/repo. I really like it and I really appreciate it.

I am amazed that you got MusicBERT to work. It is such a bulky/messy implementation/model. I spend like 2 days trying to mke it work and failed. So you did a great job! Thank you.

Secondly, I wanted to invite you to check out my mid-scale multi-instrumental model/implementation. It is much easier to use, and work with and it produces similar results. Here is the link:

https://github.com/asigalov61/Mini-Muse

And last but not least, I wanted to ask you if you would be interested in collabing to create a proper, easy-to-use, large-scale multi-instrumental model? I have MIDIs and I can take care of the training, but I need help with implementation and other technical stuff to make it nice and interesting.

Let me know.

Most sincerely,

Alex

**Comment by AniketRajpoot** [comment]
Hello @asigalov61, 
I hope you are doing well! Arpan and I are working on MIDI from a long time and glad you like our work. 
I am really amazed you were able to create a mini Muse-net, I will check it thoroughly soon. 
We are really interested in working with you to make a large scale multi instrument model and even deploy it for public use, also we have ideas of our own which we can discuss and implement them if possible. 

You can either contact me or Arpan directly anytime. 
Looking forward to your reply :)

**Comment by asigalov61** [comment]
@AniketRajpoot Replied to your email as you have offered. Looking forward to hearing from you :)
